In [1]:
from checkmybus import CheckMyBusClient, CheckMyBusSearchParams

In [25]:
client = CheckMyBusClient()
result = client.search(CheckMyBusSearchParams(
    departure_location="Münich",
    departure_date="2026-04-16",
    arrival_location="Venice Airport, VCE, Italy",
))

In [26]:
df = result.to_dataframe()

In [27]:
df.tail()

,company,operator,origin_city,origin_station,dest_city,dest_station,departure_dt,arrival_dt,duration_min,duration_str,...,currency,price_formatted,transport_mode,stops,free_seats,seat_class,sold_out,deep_link,checkmybus_url,source
0,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 03:05:00,2026-04-16 13:45:00,640,10h 40m,...,EUR,€42.47,bus,1,62,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
1,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 08:00:00,2026-04-16 17:15:00,555,9h 15m,...,EUR,€30.98,bus,0,70,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
2,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 13:45:00,2026-04-16 23:55:00,610,10h 10m,...,EUR,€42.47,bus,1,35,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
3,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 23:15:00,2026-04-17 07:40:00,505,8h 25m,...,EUR,€41.98,bus,0,50,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
4,FlixBus,FlixBus,Munich,Central Bus Station,Pitomača,Ul. Ljudevita Gaja,2026-04-16 23:40:00,2026-04-17 10:35:00,655,10h 55m,...,EUR,€31.98,bus,0,67,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus

In [28]:
df[df['transport_mode']=="train"]

Empty DataFrame
Columns: [company, operator, origin_city, origin_station, dest_city, dest_station, departure_dt, arrival_dt, duration_min, duration_str, price, currency, price_formatted, transport_mode, stops, free_seats, seat_class, sold_out, deep_link, checkmybus_url, source]
Index: []

[0 rows x 21 columns]

In [29]:
df["transport_mode"].unique()

<StringArray>
['bus']
Length: 1, dtype: str

In [30]:
df

,company,operator,origin_city,origin_station,dest_city,dest_station,departure_dt,arrival_dt,duration_min,duration_str,...,currency,price_formatted,transport_mode,stops,free_seats,seat_class,sold_out,deep_link,checkmybus_url,source
0,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 03:05:00,2026-04-16 13:45:00,640,10h 40m,...,EUR,€42.47,bus,1,62,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
1,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 08:00:00,2026-04-16 17:15:00,555,9h 15m,...,EUR,€30.98,bus,0,70,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
2,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 13:45:00,2026-04-16 23:55:00,610,10h 10m,...,EUR,€42.47,bus,1,35,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
3,FlixBus,FlixBus,Munich,Central Bus Station,Venice Airport,Venice Airport,2026-04-16 23:15:00,2026-04-17 07:40:00,505,8h 25m,...,EUR,€41.98,bus,0,50,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus
4,FlixBus,FlixBus,Munich,Central Bus Station,Pitomača,Ul. Ljudevita Gaja,2026-04-16 23:40:00,2026-04-17 10:35:00,655,10h 55m,...,EUR,€31.98,bus,0,67,Economy,False,None,https://www.checkmybus.com/munich/venice-airpo...,checkmybus