In [3]:
import json
import pandas as pd

with open("../airports.json") as f:
    raw = json.load(f)

# raw is: {"00AK": {...}, "00AL": {...}, ...}
# pd.DataFrame.from_dict with orient="index" makes each key a row
df = pd.DataFrame.from_dict(raw, orient="index")
# Step 1: keep only Italy and Germany
df = df[df["country"].isin(["IT", "DE"])]

# Step 2: keep only airports that have an IATA code (commercial airports)
df = df[df["iata"] != ""]

# Step 3: reset index so row numbers are clean
df = df.reset_index(drop=True)

print(df)

     icao iata                                               name  \
0    EDAC  AOC                           Altenburg-Nobitz Airport
1    EDAH  HDF                                Heringsdorf Airport
2    EDAQ  ZHZ                                Halle-Oppin Airport
3    EDAU  IES                               Riesa-Gohlis Airport
4    EDAX  REB                               Rechlin-Larz Airport
..    ...  ...                                                ...
173  LIRN  NAP         Napoli / Capodichino International Airport
174  LIRP  PSA  Pisa / San Giusto - Galileo Galilei Internatio...
175  LIRQ  FLR                         Firenze / Peretola Airport
176  LIRS  GRS                                   Grosseto Airport
177  LIRZ  PEG                       Perugia / San Egidio Airport

            city                   state country  elevation        lat  \
0      Altenburg               Thuringia      DE        640  50.981945
1    Heringsdorf  Mecklenburg-Vorpommern      DE         93  53.878700
2          Oppin           Saxony-Anhalt      DE        348  51.552223
3          Riesa                  Saxony      DE        322  51.293610
4           Larz  Mecklenburg-Vorpommern      DE        220  53.306389
..           ...                     ...     ...        ...        ...
173       Napoli                Campania      IT        294  40.886002
174         Pisa                 Tuscany      IT          6  43.683899
175      Firenze                 Tuscany      IT        142  43.810001
176     Grosetto                 Tuscany      IT         17  42.759701
177      Perugia                  Umbria      IT        697  43.095901

           lon             tz
0    12.506389  Europe/Berlin
1    14.152300  Europe/Berlin
2    12.053889  Europe/Berlin
3    13.356111  Europe/Berlin
4    12.752222  Europe/Berlin
..         ...            ...
173  14.290800    Europe/Rome
174  10.392700    Europe/Rome
175  11.205100    Europe/Rome
176  11.071900    Europe/Rome
177  12.513200    Europe/Rome

[178 rows x 10 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   icao       178 non-null    str
 1   iata       178 non-null    str
 2   name       178 non-null    str
 3   city       178 non-null    str
 4   state      178 non-null    str
 5   country    178 non-null    str
 6   elevation  178 non-null    int64
 7   lat        178 non-null    float64
 8   lon        178 non-null    float64
 9   tz         178 non-null    str
dtypes: float64(2), int64(1), str(7)
memory usage: 14.0 KB

In [5]:
df.head()

,icao,iata,name,city,state,country,elevation,lat,lon,tz
0,EDAC,AOC,Altenburg-Nobitz Airport,Altenburg,Thuringia,DE,640,50.981945,12.506389,Europe/Berlin
1,EDAH,HDF,Heringsdorf Airport,Heringsdorf,Mecklenburg-Vorpommern,DE,93,53.878700,14.152300,Europe/Berlin
2,EDAQ,ZHZ,Halle-Oppin Airport,Oppin,Saxony-Anhalt,DE,348,51.552223,12.053889,Europe/Berlin
3,EDAU,IES,Riesa-Gohlis Airport,Riesa,Saxony,DE,322,51.293610,13.356111,Europe/Berlin
4,EDAX,REB,Rechlin-Larz Airport,Larz,Mecklenburg-Vorpommern,DE,220,53.306389,12.752222,Europe/Berlin

In [9]:
import difflib
name = input("Input the name of the airport: ")
matches = difflib.get_close_matches(name, df["name"], n=3)

In [10]:
matches

[]

In [11]:
from thefuzz import process
best_match = process.extract(name, df["name"], limit=5)

In [12]:
best_match

[('Frankfurt am Main International Airport', 90, 15),
 ('Frankfurt-Egelsbach Airport', 90, 29),
 ('Frankfurt-Hahn Airport', 90, 30),
 ('Verona / Villafranca Airport', 72, 160),
 ('Berlin Brandenburg Airport', 54, 12)]

In [13]:
df

,icao,iata,name,city,state,country,elevation,lat,lon,tz
0,EDAC,AOC,Altenburg-Nobitz Airport,Altenburg,Thuringia,DE,640,50.981945,12.506389,Europe/Berlin
1,EDAH,HDF,Heringsdorf Airport,Heringsdorf,Mecklenburg-Vorpommern,DE,93,53.878700,14.152300,Europe/Berlin
2,EDAQ,ZHZ,Halle-Oppin Airport,Oppin,Saxony-Anhalt,DE,348,51.552223,12.053889,Europe/Berlin
3,EDAU,IES,Riesa-Gohlis Airport,Riesa,Saxony,DE,322,51.293610,13.356111,Europe/Berlin
4,EDAX,REB,Rechlin-Larz Airport,Larz,Mecklenburg-Vorpommern,DE,220,53.306389,12.752222,Europe/Berlin
...,...,...,...,...,...,...,...,...,...,...
173,LIRN,NAP,Napoli / Capodichino International Airport,Napoli,Campania,IT,294,40.886002,14.290800,Europe/Rome
174,LIRP,PSA,Pisa / San Giusto - Galileo Galilei Internatio...,Pisa,Tuscany,IT,6,43.683899,10.392700,Europe/Rome
175,LIRQ,FLR,Firenze / Peretola Airport,Firenze,Tuscany,IT,142,43.810001,11.205100,Europe/Rome
176,LIRS,GRS,Grosseto Airport,Grosetto,Tuscany,IT,17,42.759701,11.071900,Europe/Rome
177,LIRZ,PEG,Perugia / San Egidio Airport,Perugia,Umbria,IT,697,43.095901,12.513200,Europe/Rome